/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.miniproyecto;

/**
 *
 * @author cgamb
 */
public class PantallaSuscripciones extends javax.swing.JFrame {
    private Suscripcion[] arregloSuscripciones; 
    private int contador = 0;
    
    

    /**
     * Creates new form PantallaSuscripciones
     */
    public PantallaSuscripciones() {
        initComponents();
        this.jTextField1.setText("");
        this.jTextField3.setText("");
        this.jTextField4.setText("");
        this.jTextField5.setText("");
        this.jTextField6.setText("");
        this.jTextField7.setText("");
        this.jTextField8.setText("");
        
        // Ponemos el mensaje de inicio
        this.jLabel2.setText("Esperando registro.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¿Cuántas suscripciones vas a registrar (5-15)?");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Fijar Límite");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Ingresar Datos");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Ordenar por Costo");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Mostrar Todos");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Salir");
        jButton5.setToolTipText("");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Buscar");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Esperando registro.");

        jTextField3.setText("jTextField3");

        jLabel3.setText("Servicio:");

        jTextField4.setText("jTextField4");

        jLabel4.setText("Plan:");

        jTextField5.setText("jTextField5");

        jLabel5.setText("Método de Pago:");

        jTextField6.setText("jTextField6");

        jLabel6.setText("Moneda:");

        jTextField7.setText("jTextField7");

        jLabel7.setText("Costo Mensual:");

        jTextField8.setText("jTextField8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(157, 157, 157))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(jTextField5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(62, 62, 62)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(629, 629, 629))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(350, 350, 350))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(55, 55, 55)
                .addComponent(jButton5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String textoLimite = this.jTextField1.getText().trim();
        
        int tamano = Integer.parseInt(textoLimite);
        
        if (tamano >= 5 && tamano <= 15) {
            arregloSuscripciones = new Suscripcion[tamano];
            
            this.jLabel1.setText("Fijado en: " + tamano + " :ahora ya puede continuar");
            // para bloquear por si ingresa texto o numero
            this.jTextField1.setEnabled(false);
            
        } else {
            // Si meten un 3 o un 20...
            this.jLabel1.setText("Hey, el numero debe estar entre 5 y 15");
        }
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Verificamos que haya algo que mostrar
        if (contador == 0) {
            this.jLabel2.setText("No hay suscripciones registrdo.");
            return;
        }
        
        StringBuilder textoAMostrar = new StringBuilder();
        
        for (int i = 0; i < contador; i++) {
            textoAMostrar.append("Suscripción [").append(i + 1).append("] -> ")
                         .append(arregloSuscripciones[i].toString())
                         .append("\n"); // Salto de línea
        }
        
        this.jTextArea1.setText(textoAMostrar.toString());
        this.jLabel2.setText("Mostrar todas las suscripciones");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (contador == 0) {
            this.jLabel2.setText("No hay infi para ordenar");
            return;
        }

        //por seleccion
        for (int i = 0; i < contador - 1; i++) {
            int indiceMenor = i;
            for (int j = i + 1; j < contador; j++) {
                // Comparamos los costos (si el de J es menor que el de indiceMenor)
                if (arregloSuscripciones[j].getCostoMensual() < arregloSuscripciones[indiceMenor].getCostoMensual()) {
                    indiceMenor = j;
                }
            }
            // Hacemos el intercambio (swap) de los objetos completos
            Suscripcion temporal = arregloSuscripciones[indiceMenor];
            arregloSuscripciones[indiceMenor] = arregloSuscripciones[i];
            arregloSuscripciones[i] = temporal;
        }
        // para mistrar
        StringBuilder textoAMostrar = new StringBuilder();
        for (int i = 0; i < contador; i++) {
            textoAMostrar.append("Suscripción [").append(i + 1).append("] -> ")
                         .append(arregloSuscripciones[i].toString())
                         .append("\n");
        }
        this.jTextArea1.setText(textoAMostrar.toString());
        
        this.jLabel2.setText("Ordenado por Costo de menor a mayor");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (arregloSuscripciones == null) {
            this.jLabel2.setText("Hey primero fija el limite");
            return; 
        }
        
        if (contador < arregloSuscripciones.length) {
            String servicio = this.jTextField4.getText().trim();
            String plan = this.jTextField5.getText().trim();
            String pago = this.jTextField6.getText().trim();
            String moneda = this.jTextField7.getText().trim();
            String textoCosto = this.jTextField8.getText().trim();
            
            Double costo = Double.parseDouble(textoCosto);
            
            arregloSuscripciones[contador] = new Suscripcion
                                            (servicio, plan, pago, moneda, costo);
            contador++;
            
            this.jTextField4.setText("");
            this.jTextField5.setText("");
            this.jTextField6.setText("");
            this.jTextField7.setText("");
            this.jTextField8.setText("");
            
            this.jLabel2.setText("Suscripcion agregado, ahora llevas: "
                                + contador + " de " + arregloSuscripciones.length);
            
            
            /// mostrar pantalla
            StringBuilder textoAMostrar = new StringBuilder();
            for (int i = 0; i < contador; i++){
                textoAMostrar.append("Suscripción [").append(i + 1).append("] -> ")
                             .append(arregloSuscripciones[i].toString())
                             .append("\n");
            }
            this.jTextArea1.setText(textoAMostrar.toString());
            
        } else {
            this.jLabel2.setText("Ya ingresaste lo maximo, F, ya no se ppuede mas");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (contador == 0) {
            this.jLabel2.setText("Esto esta vacio");
            return;
        }
        
        String palabraClave = this.jTextField3.getText().trim();
        boolean encontrado = false;
        
        // Búsqueda lineal manual
        for (int i = 0; i < contador; i++) {
            // comparar si es igual o no
            if (arregloSuscripciones[i].getServicio().equalsIgnoreCase(palabraClave)) {
                this.jTextArea1.setText("Busqueda listo \n\n" + arregloSuscripciones[i].toString());
                this.jLabel2.setText("Suscripcion encontrada en la posicion [" + (i + 1) + "]");
                encontrado = true;
                break;
            }
        }
        if (encontrado == false) {
            this.jTextArea1.setText("");
            this.jLabel2.setText("No se encontro ninguna suscripcion" + palabraClave);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       PantallaSuscripciones ventana = new PantallaSuscripciones();
        ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
